version: '3.1'

services:
  odoo-web:
    image: odoo:16.0
    depends_on:
      odoo-db:
        condition: service_started
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    container_name: odoo-web

  odoo-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoodb
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    container_name: odoo-db

volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: ./config/odoo_pg_pass.txt